### ISSUE TITLE
Split simplepush, webpush, not found into separate derived streams

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/push-service#23]
We've had all of the endpoint log data (which has until recently been nearly all simplepush data) going into a single set of redshift tables. It would be more useful to have the simplepush and webpush data going into separate streams for independent analysis. Some notifications aren't delivered to either due to being sent to an endpoint that no longer exists; these will now going into a third set of redshift tables.

Implemented and awaiting deployment as tracked in [bug 1247036](https://bugzilla.mozilla.org/show_bug.cgi?id=1247036).

**Comment by bbangert** [comment]
This has been done already.
