### ISSUE TITLE
Update endpoint calculation queries

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/push-service#24]
Currently endpoint count is simple count of unique channel_ids. We've since learned that this can't be trusted, b/c the Hello client reuses the same hard-coded channel id for every recipient, so endpoint count needs to be redefined as a unique channel_id/uaid_hash pair. Report queries need to be updated to reflect this.

Implemented and awaiting deployment as tracked in [bug 1247036](https://bugzilla.mozilla.org/show_bug.cgi?id=1247036).

**Comment by bbangert** [comment]
Not need as new python script does this.
