### ISSUE TITLE
Write blog post on VAPID auth header

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-service#27]
A blog post should be written and posted to the services blog about including a VAPID auth header with email details, and why that's helpful.

**Comment by jrconlin** [comment]
https://docs.google.com/a/mozilla.com/document/d/1oqXKS-Ze4Jcdb43m3G09Q9WcJZvSqq_uruqazZ1DHNg/edit?usp=sharing

**Comment by jrconlin** [comment]
Pending landing of Restricted Subscription support in nightly.

**Comment by jrconlin** [comment]
Posted
