### ISSUE TITLE
Update MAU / DAU values in report to come from Push ACKs

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/push-service#30]
Currently all "receiver" values in the nightly Push metrics report are based on notifications being sent through the Endpoint server. Clearly, however, users can't be considered "active" unless they're actually using Firefox and receiving these notifications, so we want to update some of these values to be driven by the newly available ACK records from the Push server logs.

Blocked by #28.

**Comment by bbangert** [comment]
Handled by new script already.
