### ISSUE TITLE
Impact of B2G demise and Mozilla focus on core competencies 

### ISSUE THREAD

**Issue by RichardMaher** [mozilla-services/push-service#35]
As Mozilla continues to sharpen its focus on development around its Firefox browser, is it not only a matter of time before the Mozilla Push-Service is deprioritized and/or sold?

Should efforts now be focused on getting FireFox to work with GCM, WNS, APNs, and AWS etc? With autopush https://mozilla-push-service.readthedocs.org/en/latest/#mozilla-push-service already lagging way behind industry-standard and industry-strength offerings from established Cloud Service Providers can you please concentrate on exposing all available Push Features into the UI?

For example: -
Broadcasting
Topic-Based subscriptions
Globalization/Localization
Collapse_Key
Priority
TTL

Surely, the good news is that you no longer have to re-invent the wheel and can focus on continuing to improve that great core product FireFox?

Cheers Richard

**Comment by bbangert** [comment]
Mozilla will be supporting this service as a core browser component.
