### ISSUE TITLE
Create page of resources for contributors and developers

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/push-service#42]
Since we have a public facing component, we're going to get a lot of questions and concerns about some of the systems we touch and use.

We should create a page that links to things like:
Learn more about Web Notifications:
https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API

File a bug about Notification formatting or presentation:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Notifications%20and%20Alerts

Enable debugging, etc.

**Comment by bbangert** [comment]
Where should this page live?

**Comment by bbangert** [comment]
Superceded by #92 to address multiple clean-ups, to answer my prior question, this page will live with the rest of the main documents in the RTD page.
