### ISSUE TITLE
Update webpush to use ECE Draft spec 07

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/push-service#53]
See: https://github.com/web-push-libs/pywebpush/issues/33
https://tools.ietf.org/html/draft-ietf-httpbis-encryption-encoding-07

**Comment by jrconlin** [comment]
Client work is still outstanding for this issue.

**Comment by jrconlin** [comment]
@kitcambridge Curious what the state of this issue is. As I understand, there may be a ece clib that handles the new encryption format, so would mobile devices benefit? Desktop would require a bit of tweaking to handle the differing formats since it uses js, right?

**Comment by ghost** [comment]
iOS should work out of the box with aes128gcm. https://bugzilla.mozilla.org/show_bug.cgi?id=1345665 has a patch for Desktop and Android, I'll incorporate Martin's review feedback and submit a new patch this week.

**Comment by jrconlin** [comment]
closing. fixed. aes128gcm supported on all firefox devices.

**Comment by bbangert** [comment]
Referenced issues have been resolved.
