### ISSUE TITLE
Docs: Document the crypto key for endpoints

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-service#6]
It's not clear on why the UAID/CHID are encrypted when used for the endpoint, even though there's a good reason for it. The reasons and methodology for the crypto should be documented.

**Comment by jrconlin** [comment]
Committed in https://github.com/mozilla-services/autopush/commit/a59358a1526e7476d4c096cd6cf010aafc8d2f22

**Comment by jrconlin** [comment]
Merged via PR #257 https://github.com/mozilla-services/autopush/pull/257/commits
