### ISSUE TITLE
Test autopush/endpoint w/ low MALLOC_ARENA_MAX values and jemalloc

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/push-service#79]
We appear to be suffering from glibc malloc using excessive memory w/ our allocation patterns, similar to the situation described here:

http://codearcana.com/posts/2016/07/11/arena-leak-in-glibc.html

We need to see what memory improvements can be seen w/ autopush/endpoint under a MALLOC_ARENA_MAX=1

We currently have a couple nodes running at a more conservative MALLOC_ARENA_MAX=2. We're still seeing the same rate of growth, however the total RSS used has been cut by about 33% under endpoint, and about 20% under autopush.

**Comment by pjenvey** [comment]
Also jemalloc may show more improvement over glibc malloc, support for enabling it was added in https://github.com/mozilla-services/autopush/issues/1100

**Comment by bbangert** [comment]
Memory use is pretty solid now and the crypto is faster. Remaining work is obsolete per Rust move this year.
