### ISSUE TITLE
Write up mozilla proprietary websocket protocol for WebPush

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/push-service#82]
Write a document describing the current web socket based JSON packet exchange. 

It's tribal knowledge at this point, and that's terrible.

**Comment by bbangert** [comment]
Isn't this already present at http://mozilla-push-service.readthedocs.io/en/latest/design/#simplepush-protocol, perhaps it just needs to be renamed?

**Comment by jrconlin** [comment]
It is. that's what #83 does.

**Comment by bbangert** [comment]
Closing in favor of #82.
