### ISSUE TITLE
Fully document autopush Bridge creation

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/push-service#87]
Outside teams need to understand how to create bridges for Autopush. 

Currently, this is the responsibility of one engineer, which is bad.

**Comment by jrconlin** [comment]
https://docs.google.com/document/d/19FKc6FFJI9mPndU_RxEW7NRtkARnik8Hlyve8UT5jBM/edit?usp=sharing

**Comment by bbangert** [comment]
This looks good, I'll merge it with the RTD docs in #92.
